/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TalentsRouteImport } from './routes/talents'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as RecruitmentRouteImport } from './routes/recruitment'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIdRouteImport } from './routes/teams.$id'
import { Route as TalentsIdRouteImport } from './routes/talents.$id'
import { Route as TalentTeamsRouteImport } from './routes/talent.teams'
import { Route as TalentSubmissionsRouteImport } from './routes/talent.submissions'
import { Route as TalentSettingsRouteImport } from './routes/talent.settings'
import { Route as TalentProfileRouteImport } from './routes/talent.profile'
import { Route as TalentOnboardingRouteImport } from './routes/talent.onboarding'
import { Route as TalentMessagesRouteImport } from './routes/talent.messages'
import { Route as TalentDashboardRouteImport } from './routes/talent.dashboard'
import { Route as TalentChallengesRouteImport } from './routes/talent.challenges'
import { Route as TalentCareerRouteImport } from './routes/talent.career'
import { Route as RecruitmentIdRouteImport } from './routes/recruitment.$id'
import { Route as MatchIdRouteImport } from './routes/match.$id'
import { Route as CompanySettingsRouteImport } from './routes/company.settings'
import { Route as CompanyRecruitmentRouteImport } from './routes/company.recruitment'
import { Route as CompanyOnboardingRouteImport } from './routes/company.onboarding'
import { Route as CompanyMessagesRouteImport } from './routes/company.messages'
import { Route as CompanyDashboardRouteImport } from './routes/company.dashboard'
import { Route as CompanyChallengesRouteImport } from './routes/company.challenges'
import { Route as CompanyCandidatesRouteImport } from './routes/company.candidates'
import { Route as CompanyAnalyticsRouteImport } from './routes/company.analytics'
import { Route as ChallengesIdRouteImport } from './routes/challenges.$id'
import { Route as AdminTalentsRouteImport } from './routes/admin.talents'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminMatchesRouteImport } from './routes/admin.matches'
import { Route as AdminCompaniesRouteImport } from './routes/admin.companies'
import { Route as AdminChallengesRouteImport } from './routes/admin.challenges'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as CompanyChallengesIdRouteImport } from './routes/company.challenges.$id'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentsRoute = TalentsRouteImport.update({
  id: '/talents',
  path: '/talents',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRoute = RecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIdRoute = TeamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeamsRoute,
} as any)
const TalentsIdRoute = TalentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TalentsRoute,
} as any)
const TalentTeamsRoute = TalentTeamsRouteImport.update({
  id: '/talent/teams',
  path: '/talent/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentSubmissionsRoute = TalentSubmissionsRouteImport.update({
  id: '/talent/submissions',
  path: '/talent/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentSettingsRoute = TalentSettingsRouteImport.update({
  id: '/talent/settings',
  path: '/talent/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentProfileRoute = TalentProfileRouteImport.update({
  id: '/talent/profile',
  path: '/talent/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentOnboardingRoute = TalentOnboardingRouteImport.update({
  id: '/talent/onboarding',
  path: '/talent/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentMessagesRoute = TalentMessagesRouteImport.update({
  id: '/talent/messages',
  path: '/talent/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentDashboardRoute = TalentDashboardRouteImport.update({
  id: '/talent/dashboard',
  path: '/talent/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentChallengesRoute = TalentChallengesRouteImport.update({
  id: '/talent/challenges',
  path: '/talent/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentCareerRoute = TalentCareerRouteImport.update({
  id: '/talent/career',
  path: '/talent/career',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentIdRoute = RecruitmentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecruitmentRoute,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySettingsRoute = CompanySettingsRouteImport.update({
  id: '/company/settings',
  path: '/company/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRecruitmentRoute = CompanyRecruitmentRouteImport.update({
  id: '/company/recruitment',
  path: '/company/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyOnboardingRoute = CompanyOnboardingRouteImport.update({
  id: '/company/onboarding',
  path: '/company/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyMessagesRoute = CompanyMessagesRouteImport.update({
  id: '/company/messages',
  path: '/company/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyDashboardRoute = CompanyDashboardRouteImport.update({
  id: '/company/dashboard',
  path: '/company/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyChallengesRoute = CompanyChallengesRouteImport.update({
  id: '/company/challenges',
  path: '/company/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCandidatesRoute = CompanyCandidatesRouteImport.update({
  id: '/company/candidates',
  path: '/company/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyAnalyticsRoute = CompanyAnalyticsRouteImport.update({
  id: '/company/analytics',
  path: '/company/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIdRoute = ChallengesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChallengesRoute,
} as any)
const AdminTalentsRoute = AdminTalentsRouteImport.update({
  id: '/talents',
  path: '/talents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatchesRoute = AdminMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChallengesRoute = AdminChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const CompanyChallengesIdRoute = CompanyChallengesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CompanyChallengesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/recruitment': typeof RecruitmentRouteWithChildren
  '/success-stories': typeof SuccessStoriesRoute
  '/talents': typeof TalentsRouteWithChildren
  '/teams': typeof TeamsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/challenges': typeof AdminChallengesRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/talents': typeof AdminTalentsRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/company/analytics': typeof CompanyAnalyticsRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/challenges': typeof CompanyChallengesRouteWithChildren
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/messages': typeof CompanyMessagesRoute
  '/company/onboarding': typeof CompanyOnboardingRoute
  '/company/recruitment': typeof CompanyRecruitmentRoute
  '/company/settings': typeof CompanySettingsRoute
  '/match/$id': typeof MatchIdRoute
  '/recruitment/$id': typeof RecruitmentIdRoute
  '/talent/career': typeof TalentCareerRoute
  '/talent/challenges': typeof TalentChallengesRoute
  '/talent/dashboard': typeof TalentDashboardRoute
  '/talent/messages': typeof TalentMessagesRoute
  '/talent/onboarding': typeof TalentOnboardingRoute
  '/talent/profile': typeof TalentProfileRoute
  '/talent/settings': typeof TalentSettingsRoute
  '/talent/submissions': typeof TalentSubmissionsRoute
  '/talent/teams': typeof TalentTeamsRoute
  '/talents/$id': typeof TalentsIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/company/challenges/$id': typeof CompanyChallengesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/recruitment': typeof RecruitmentRouteWithChildren
  '/success-stories': typeof SuccessStoriesRoute
  '/talents': typeof TalentsRouteWithChildren
  '/teams': typeof TeamsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/challenges': typeof AdminChallengesRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/talents': typeof AdminTalentsRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/company/analytics': typeof CompanyAnalyticsRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/challenges': typeof CompanyChallengesRouteWithChildren
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/messages': typeof CompanyMessagesRoute
  '/company/onboarding': typeof CompanyOnboardingRoute
  '/company/recruitment': typeof CompanyRecruitmentRoute
  '/company/settings': typeof CompanySettingsRoute
  '/match/$id': typeof MatchIdRoute
  '/recruitment/$id': typeof RecruitmentIdRoute
  '/talent/career': typeof TalentCareerRoute
  '/talent/challenges': typeof TalentChallengesRoute
  '/talent/dashboard': typeof TalentDashboardRoute
  '/talent/messages': typeof TalentMessagesRoute
  '/talent/onboarding': typeof TalentOnboardingRoute
  '/talent/profile': typeof TalentProfileRoute
  '/talent/settings': typeof TalentSettingsRoute
  '/talent/submissions': typeof TalentSubmissionsRoute
  '/talent/teams': typeof TalentTeamsRoute
  '/talents/$id': typeof TalentsIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/company/challenges/$id': typeof CompanyChallengesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/recruitment': typeof RecruitmentRouteWithChildren
  '/success-stories': typeof SuccessStoriesRoute
  '/talents': typeof TalentsRouteWithChildren
  '/teams': typeof TeamsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/challenges': typeof AdminChallengesRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/talents': typeof AdminTalentsRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/company/analytics': typeof CompanyAnalyticsRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/challenges': typeof CompanyChallengesRouteWithChildren
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/messages': typeof CompanyMessagesRoute
  '/company/onboarding': typeof CompanyOnboardingRoute
  '/company/recruitment': typeof CompanyRecruitmentRoute
  '/company/settings': typeof CompanySettingsRoute
  '/match/$id': typeof MatchIdRoute
  '/recruitment/$id': typeof RecruitmentIdRoute
  '/talent/career': typeof TalentCareerRoute
  '/talent/challenges': typeof TalentChallengesRoute
  '/talent/dashboard': typeof TalentDashboardRoute
  '/talent/messages': typeof TalentMessagesRoute
  '/talent/onboarding': typeof TalentOnboardingRoute
  '/talent/profile': typeof TalentProfileRoute
  '/talent/settings': typeof TalentSettingsRoute
  '/talent/submissions': typeof TalentSubmissionsRoute
  '/talent/teams': typeof TalentTeamsRoute
  '/talents/$id': typeof TalentsIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/company/challenges/$id': typeof CompanyChallengesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/challenges'
    | '/recruitment'
    | '/success-stories'
    | '/talents'
    | '/teams'
    | '/admin/analytics'
    | '/admin/challenges'
    | '/admin/companies'
    | '/admin/matches'
    | '/admin/moderation'
    | '/admin/settings'
    | '/admin/talents'
    | '/challenges/$id'
    | '/company/analytics'
    | '/company/candidates'
    | '/company/challenges'
    | '/company/dashboard'
    | '/company/messages'
    | '/company/onboarding'
    | '/company/recruitment'
    | '/company/settings'
    | '/match/$id'
    | '/recruitment/$id'
    | '/talent/career'
    | '/talent/challenges'
    | '/talent/dashboard'
    | '/talent/messages'
    | '/talent/onboarding'
    | '/talent/profile'
    | '/talent/settings'
    | '/talent/submissions'
    | '/talent/teams'
    | '/talents/$id'
    | '/teams/$id'
    | '/company/challenges/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/challenges'
    | '/recruitment'
    | '/success-stories'
    | '/talents'
    | '/teams'
    | '/admin/analytics'
    | '/admin/challenges'
    | '/admin/companies'
    | '/admin/matches'
    | '/admin/moderation'
    | '/admin/settings'
    | '/admin/talents'
    | '/challenges/$id'
    | '/company/analytics'
    | '/company/candidates'
    | '/company/challenges'
    | '/company/dashboard'
    | '/company/messages'
    | '/company/onboarding'
    | '/company/recruitment'
    | '/company/settings'
    | '/match/$id'
    | '/recruitment/$id'
    | '/talent/career'
    | '/talent/challenges'
    | '/talent/dashboard'
    | '/talent/messages'
    | '/talent/onboarding'
    | '/talent/profile'
    | '/talent/settings'
    | '/talent/submissions'
    | '/talent/teams'
    | '/talents/$id'
    | '/teams/$id'
    | '/company/challenges/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/challenges'
    | '/recruitment'
    | '/success-stories'
    | '/talents'
    | '/teams'
    | '/admin/analytics'
    | '/admin/challenges'
    | '/admin/companies'
    | '/admin/matches'
    | '/admin/moderation'
    | '/admin/settings'
    | '/admin/talents'
    | '/challenges/$id'
    | '/company/analytics'
    | '/company/candidates'
    | '/company/challenges'
    | '/company/dashboard'
    | '/company/messages'
    | '/company/onboarding'
    | '/company/recruitment'
    | '/company/settings'
    | '/match/$id'
    | '/recruitment/$id'
    | '/talent/career'
    | '/talent/challenges'
    | '/talent/dashboard'
    | '/talent/messages'
    | '/talent/onboarding'
    | '/talent/profile'
    | '/talent/settings'
    | '/talent/submissions'
    | '/talent/teams'
    | '/talents/$id'
    | '/teams/$id'
    | '/company/challenges/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChallengesRoute: typeof ChallengesRouteWithChildren
  RecruitmentRoute: typeof RecruitmentRouteWithChildren
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  TalentsRoute: typeof TalentsRouteWithChildren
  TeamsRoute: typeof TeamsRouteWithChildren
  CompanyAnalyticsRoute: typeof CompanyAnalyticsRoute
  CompanyCandidatesRoute: typeof CompanyCandidatesRoute
  CompanyChallengesRoute: typeof CompanyChallengesRouteWithChildren
  CompanyDashboardRoute: typeof CompanyDashboardRoute
  CompanyMessagesRoute: typeof CompanyMessagesRoute
  CompanyOnboardingRoute: typeof CompanyOnboardingRoute
  CompanyRecruitmentRoute: typeof CompanyRecruitmentRoute
  CompanySettingsRoute: typeof CompanySettingsRoute
  MatchIdRoute: typeof MatchIdRoute
  TalentCareerRoute: typeof TalentCareerRoute
  TalentChallengesRoute: typeof TalentChallengesRoute
  TalentDashboardRoute: typeof TalentDashboardRoute
  TalentMessagesRoute: typeof TalentMessagesRoute
  TalentOnboardingRoute: typeof TalentOnboardingRoute
  TalentProfileRoute: typeof TalentProfileRoute
  TalentSettingsRoute: typeof TalentSettingsRoute
  TalentSubmissionsRoute: typeof TalentSubmissionsRoute
  TalentTeamsRoute: typeof TalentTeamsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talents': {
      id: '/talents'
      path: '/talents'
      fullPath: '/talents'
      preLoaderRoute: typeof TalentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment': {
      id: '/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof RecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$id': {
      id: '/teams/$id'
      path: '/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof TeamsIdRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/talents/$id': {
      id: '/talents/$id'
      path: '/$id'
      fullPath: '/talents/$id'
      preLoaderRoute: typeof TalentsIdRouteImport
      parentRoute: typeof TalentsRoute
    }
    '/talent/teams': {
      id: '/talent/teams'
      path: '/talent/teams'
      fullPath: '/talent/teams'
      preLoaderRoute: typeof TalentTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/submissions': {
      id: '/talent/submissions'
      path: '/talent/submissions'
      fullPath: '/talent/submissions'
      preLoaderRoute: typeof TalentSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/settings': {
      id: '/talent/settings'
      path: '/talent/settings'
      fullPath: '/talent/settings'
      preLoaderRoute: typeof TalentSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/profile': {
      id: '/talent/profile'
      path: '/talent/profile'
      fullPath: '/talent/profile'
      preLoaderRoute: typeof TalentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/onboarding': {
      id: '/talent/onboarding'
      path: '/talent/onboarding'
      fullPath: '/talent/onboarding'
      preLoaderRoute: typeof TalentOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/messages': {
      id: '/talent/messages'
      path: '/talent/messages'
      fullPath: '/talent/messages'
      preLoaderRoute: typeof TalentMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/dashboard': {
      id: '/talent/dashboard'
      path: '/talent/dashboard'
      fullPath: '/talent/dashboard'
      preLoaderRoute: typeof TalentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/challenges': {
      id: '/talent/challenges'
      path: '/talent/challenges'
      fullPath: '/talent/challenges'
      preLoaderRoute: typeof TalentChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/career': {
      id: '/talent/career'
      path: '/talent/career'
      fullPath: '/talent/career'
      preLoaderRoute: typeof TalentCareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/$id': {
      id: '/recruitment/$id'
      path: '/$id'
      fullPath: '/recruitment/$id'
      preLoaderRoute: typeof RecruitmentIdRouteImport
      parentRoute: typeof RecruitmentRoute
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/settings': {
      id: '/company/settings'
      path: '/company/settings'
      fullPath: '/company/settings'
      preLoaderRoute: typeof CompanySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/recruitment': {
      id: '/company/recruitment'
      path: '/company/recruitment'
      fullPath: '/company/recruitment'
      preLoaderRoute: typeof CompanyRecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/onboarding': {
      id: '/company/onboarding'
      path: '/company/onboarding'
      fullPath: '/company/onboarding'
      preLoaderRoute: typeof CompanyOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/messages': {
      id: '/company/messages'
      path: '/company/messages'
      fullPath: '/company/messages'
      preLoaderRoute: typeof CompanyMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/dashboard': {
      id: '/company/dashboard'
      path: '/company/dashboard'
      fullPath: '/company/dashboard'
      preLoaderRoute: typeof CompanyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/challenges': {
      id: '/company/challenges'
      path: '/company/challenges'
      fullPath: '/company/challenges'
      preLoaderRoute: typeof CompanyChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/candidates': {
      id: '/company/candidates'
      path: '/company/candidates'
      fullPath: '/company/candidates'
      preLoaderRoute: typeof CompanyCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/analytics': {
      id: '/company/analytics'
      path: '/company/analytics'
      fullPath: '/company/analytics'
      preLoaderRoute: typeof CompanyAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$id': {
      id: '/challenges/$id'
      path: '/$id'
      fullPath: '/challenges/$id'
      preLoaderRoute: typeof ChallengesIdRouteImport
      parentRoute: typeof ChallengesRoute
    }
    '/admin/talents': {
      id: '/admin/talents'
      path: '/talents'
      fullPath: '/admin/talents'
      preLoaderRoute: typeof AdminTalentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/matches': {
      id: '/admin/matches'
      path: '/matches'
      fullPath: '/admin/matches'
      preLoaderRoute: typeof AdminMatchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/challenges': {
      id: '/admin/challenges'
      path: '/challenges'
      fullPath: '/admin/challenges'
      preLoaderRoute: typeof AdminChallengesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/company/challenges/$id': {
      id: '/company/challenges/$id'
      path: '/$id'
      fullPath: '/company/challenges/$id'
      preLoaderRoute: typeof CompanyChallengesIdRouteImport
      parentRoute: typeof CompanyChallengesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminChallengesRoute: typeof AdminChallengesRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminMatchesRoute: typeof AdminMatchesRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTalentsRoute: typeof AdminTalentsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminChallengesRoute: AdminChallengesRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminMatchesRoute: AdminMatchesRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTalentsRoute: AdminTalentsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ChallengesRouteChildren {
  ChallengesIdRoute: typeof ChallengesIdRoute
}

const ChallengesRouteChildren: ChallengesRouteChildren = {
  ChallengesIdRoute: ChallengesIdRoute,
}

const ChallengesRouteWithChildren = ChallengesRoute._addFileChildren(
  ChallengesRouteChildren,
)

interface RecruitmentRouteChildren {
  RecruitmentIdRoute: typeof RecruitmentIdRoute
}

const RecruitmentRouteChildren: RecruitmentRouteChildren = {
  RecruitmentIdRoute: RecruitmentIdRoute,
}

const RecruitmentRouteWithChildren = RecruitmentRoute._addFileChildren(
  RecruitmentRouteChildren,
)

interface TalentsRouteChildren {
  TalentsIdRoute: typeof TalentsIdRoute
}

const TalentsRouteChildren: TalentsRouteChildren = {
  TalentsIdRoute: TalentsIdRoute,
}

const TalentsRouteWithChildren =
  TalentsRoute._addFileChildren(TalentsRouteChildren)

interface TeamsRouteChildren {
  TeamsIdRoute: typeof TeamsIdRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsIdRoute: TeamsIdRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

interface CompanyChallengesRouteChildren {
  CompanyChallengesIdRoute: typeof CompanyChallengesIdRoute
}

const CompanyChallengesRouteChildren: CompanyChallengesRouteChildren = {
  CompanyChallengesIdRoute: CompanyChallengesIdRoute,
}

const CompanyChallengesRouteWithChildren =
  CompanyChallengesRoute._addFileChildren(CompanyChallengesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ChallengesRoute: ChallengesRouteWithChildren,
  RecruitmentRoute: RecruitmentRouteWithChildren,
  SuccessStoriesRoute: SuccessStoriesRoute,
  TalentsRoute: TalentsRouteWithChildren,
  TeamsRoute: TeamsRouteWithChildren,
  CompanyAnalyticsRoute: CompanyAnalyticsRoute,
  CompanyCandidatesRoute: CompanyCandidatesRoute,
  CompanyChallengesRoute: CompanyChallengesRouteWithChildren,
  CompanyDashboardRoute: CompanyDashboardRoute,
  CompanyMessagesRoute: CompanyMessagesRoute,
  CompanyOnboardingRoute: CompanyOnboardingRoute,
  CompanyRecruitmentRoute: CompanyRecruitmentRoute,
  CompanySettingsRoute: CompanySettingsRoute,
  MatchIdRoute: MatchIdRoute,
  TalentCareerRoute: TalentCareerRoute,
  TalentChallengesRoute: TalentChallengesRoute,
  TalentDashboardRoute: TalentDashboardRoute,
  TalentMessagesRoute: TalentMessagesRoute,
  TalentOnboardingRoute: TalentOnboardingRoute,
  TalentProfileRoute: TalentProfileRoute,
  TalentSettingsRoute: TalentSettingsRoute,
  TalentSubmissionsRoute: TalentSubmissionsRoute,
  TalentTeamsRoute: TalentTeamsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
